name: Setup macOS environment
description: >-
  Installs necessary packages via Homebrew.

inputs: {} # nothing?

outputs: {} # nothing?

runs:
  using: composite

  steps:
    - name: brew
      id: brew
      shell: bash
      run: |
        formulae=(gmp libffi openssl@1.1 zlib autoconf automake libtool readline)
        brew install --quiet "${formulae[@]}"
        echo keg_only=$(brew info --json "${formulae[@]}" |
          sed -n '/^ *"name": "\(.*\)",.*/{s//\1/;h;};/^ *"keg_only": true/{g;p;}'
        ) > $GITHUB_OUTPUT

    - name: Set ENV
      shell: bash
      run: |
        CONFIGURE_ARGS="${CONFIGURE_ARGS:+$CONFIGURE_ARGS }--with-opt-dir=$(brew --prefix)"
        for lib in ${{ steps.brew.outputs.keg_only }}; do
          CONFIGURE_ARGS="${CONFIGURE_ARGS} --with-${lib%@*}-dir=$(brew --prefix $lib)"
        done
        echo CONFIGURE_ARGS="${CONFIGURE_ARGS}" >> $GITHUB_ENV
