name: Setup macOS environment
description: >-
  Installs necessary packages via Homebrew.

inputs:
  corelibs:
    required: false
    default: 'gmp'
    description: >-
      Libraries for ruby core.

  extlibs:
    required: false
    default: 'libffi openssl@3 zlib'
    description: >-
      Libraries for extensions.

  extopts:
    required: false
    default: ''
    description: >-
      Additional options to be added to the CONFIGURE_ARGS environment
      variable for extensions.

outputs:
  coreopts:
    value: ${{ steps.libs.outputs.coreopts }}
    description: >-
      Options for configure.

  extopts:
    value: ${{ steps.libs.outputs.extopts }}
    description: >-
      Options for extensions.

runs:
  using: composite

  steps:
    - id: libs
      name: libs
      run: |
        #!ruby
        corelibs, extlibs = ENV.values_at(*%w"corelibs extlibs").map do |libs|
          libs.split(" ").each_with_object([]) do |l, list|
            if l.start_with?("no-")
              list.delete {|n| File.fnmatch?(l[3..-1], n)}
            else
              list << l
            end
          end
        end

        brew = [*%w"brew install --quiet autoconf automake libtool", *corelibs, *extlibs]
        puts "::group::\e[93m#{brew.join(" ")}\e[m"
        system(*brew)
        puts "::endgroup::"

        brewed = ->(lib) {%x(brew --prefix #{lib}).chomp}
        File.open($GITHUB_OUTPUT, "a") do |f|
          coreopts = "coreopts=" + corelibs.map(brewed).uniq.join(":")

          extopts = "extopts=" + [
            ENV["extopts"],
            corelibs.map {|lib| "--with-#{lib.sub(/@.*/, "")}-dir=#{brewed[lib]}"}
          ].compact.join(" ")
          [coreopts, extopts].each do |opts|
            puts "\e[96m#{opts}\e[m"
            f.puts opts
          end
        end
      shell: ruby -S {0} -GITHUB_OUTPUT=${{ env.GITHUB_OUTPUT }}
      env:
        corelibs: gmp ${{ inputs.corelibs }}
        extlibs: libffi openssl@3 zlib ${{ inputs.extlibs }}
        extopts: ${{ inputs.extopts }}
