name: bundled_gems

on:
  push:
    branches: ['master']
    paths:
      - '.github/workflows/bundled_gems.yml'
      - 'gems/bundled_gems'
  pull_request:
    branches: ['master']
    paths:
      - '.github/workflows/bundled_gems.yml'
      - 'gems/bundled_gems'
  merge_group:
    branches: ['master']
    paths:
      - '.github/workflows/bundled_gems.yml'
      - 'gems/bundled_gems'
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch:

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  update:
    permissions:
      contents: write # for Git to git push

    if: ${{ github.event_name != 'schedule' || github.repository == 'ruby/ruby' }}

    name: update ${{ github.workflow }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: ./.github/actions/setup/directories

      - name: Set ENV
        run: |
          echo "TODAY=$(date +%F)" >> $GITHUB_ENV

      - name: Download previous gems list
        run: |
          data=bundled_gems.json
          mkdir -p .downloaded-cache
          ln -s .downloaded-cache/$data .
          curl -O -R -z ./$data https://stdgems.org/$data

      - name: Update bundled gems list
        run: |
          ruby -i~ tool/update-bundled_gems.rb gems/bundled_gems

      - name: Maintain updated gems list in NEWS
        run: |
          ruby tool/update-NEWS-gemlist.rb bundled

      - name: Check diffs
        id: diff
        run: |
          news= gems=
          git diff --color --no-ext-diff --ignore-submodules --exit-code -- NEWS.md ||
          news=true
          git diff --color --no-ext-diff --ignore-submodules --exit-code -- gems/bundled_gems ||
          gems=true
          git add -- NEWS.md gems/bundled_gems
          echo news=$news >> $GITHUB_OUTPUT
          echo gems=$gems >> $GITHUB_OUTPUT
          echo update=${news:-$gems} >> $GITHUB_OUTPUT

      - name: Install libraries
        uses: ./.github/actions/setup/ubuntu
        if: ${{ steps.diff.outpus.gems }}

      - name: Build
        run: |
          ./autogen.sh
          ./configure -C --disable-install-doc
          make
        if: ${{ steps.diff.outpus.gems }}

      - name: Prepare bundled gems
        run: |
          make -s prepare-gems
        if: ${{ steps.diff.outpus.gems }}

      - name: Test bundled gems
        run: |
          make -s test-bundled-gems
        timeout-minutes: 30
        env:
          RUBY_TESTOPTS: '-q --tty=no'
          TEST_BUNDLED_GEMS_ALLOW_FAILURES: ''
        if: ${{ steps.diff.outpus.gems }}

      - name: Commit
        run: |
          branch="bundled_gems-list-${TODAY}"
          git checkout -b "$branch" "${GITHUB_REF_NAME}"
          message="[DOC] Update bundled gems list at "
          if [ ! "$gems" ]; then
            git commit --message="${message}${GITHUB_SHA:0:30}"
          else
            git commit --message="${message}${TODAY}"
          fi
          git log "${GITHUB_REF_NAME}..HEAD"
          git push --set-upstream origin "$branch"
          gh pr create --repo "${GITHUB_REPOSITORY}" --base "${GITHUB_REF_NAME}" --fill --body ''
        env:
          EMAIL: svn-admin@ruby-lang.org
          GIT_AUTHOR_NAME: git
          GIT_COMMITTER_NAME: git
          GH_TOKEN: ${{ github.token }}
          gems: ${{ steps.diff.outputs.gems }}
        if: >-
          # github.repository == 'ruby/ruby' &&
          ${{
          !startsWith(github.event_name, 'pull') &&
          (steps.diff.outputs.update)
          }}

      - uses: ./.github/actions/slack
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: ${{ failure() }}
