name: Windows
on: [push, pull_request]
jobs:
  make:
    strategy:
      matrix:
        include:
          - vs: 2019
            os: windows-2019
            vcvars: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
          # - vs: 2022
          #   os: windows-2022
          #   vcvars: '"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvars64.bat"'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: VisualStudio ${{ matrix.vs }}
    env:
      GITPULLOPTIONS: --no-tags origin ${{github.ref}}
      VCVARS: ${{ matrix.vcvars }}
      PATCH: C:\msys64\usr\bin\patch.exe
    steps:
      - run: md build
        working-directory:
      - name: nmake test-all
        timeout-minutes: 60
        run: |
          false
        continue-on-error: ${{ matrix.continue-on-error || false }}
      - name: nmake test-spec
        timeout-minutes: 10
        run: |
          echo ok
        continue-on-error: ${{ matrix.continue-on-error || false }}

defaults:
  run:
    working-directory: build
    shell: cmd
